# Generated by Django 3.2.2 on 2021-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='User e-mail')),
                ('subject', models.CharField(max_length=100, verbose_name='Message subject')),
                ('message', models.TextField(verbose_name='Message text')),
                ('processed', models.BooleanField(default=False, verbose_name='Is form processed')),
            ],
            options={
                'verbose_name': 'User message',
                'verbose_name_plural': 'User messages',
                'db_table': 'user_messages',
            },
        ),
    ]
