# Generated by Django 3.2.2 on 2021-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_dealer',
            field=models.BooleanField(null=True, verbose_name='Is dealer'),
        ),
    ]
